package com.sufyan.hidtools.hid

object HidKeyCode {

    const val MOD_NONE: Byte = 0x00
    const val MOD_L_CTRL: Byte = 0x01
    const val MOD_L_SHIFT: Byte = 0x02
    const val MOD_L_ALT: Byte = 0x04
    const val MOD_L_META: Byte = 0x08
    const val MOD_R_CTRL: Byte = 0x10
    const val MOD_R_SHIFT: Byte = 0x20
    const val MOD_R_ALT: Byte = 0x40
    const val MOD_R_META: Byte = -128

    val KEY_A = 0x04.toByte()
    val KEY_B = 0x05.toByte()
    val KEY_C = 0x06.toByte()
    val KEY_D = 0x07.toByte()
    val KEY_E = 0x08.toByte()
    val KEY_F = 0x09.toByte()
    val KEY_G = 0x0A.toByte()
    val KEY_H = 0x0B.toByte()
    val KEY_I = 0x0C.toByte()
    val KEY_J = 0x0D.toByte()
    val KEY_K = 0x0E.toByte()
    val KEY_L = 0x0F.toByte()
    val KEY_M = 0x10.toByte()
    val KEY_N = 0x11.toByte()
    val KEY_O = 0x12.toByte()
    val KEY_P = 0x13.toByte()
    val KEY_Q = 0x14.toByte()
    val KEY_R = 0x15.toByte()
    val KEY_S = 0x16.toByte()
    val KEY_T = 0x17.toByte()
    val KEY_U = 0x18.toByte()
    val KEY_V = 0x19.toByte()
    val KEY_W = 0x1A.toByte()
    val KEY_X = 0x1B.toByte()
    val KEY_Y = 0x1C.toByte()
    val KEY_Z = 0x1D.toByte()

    val KEY_1 = 0x1E.toByte()
    val KEY_2 = 0x1F.toByte()
    val KEY_3 = 0x20.toByte()
    val KEY_4 = 0x21.toByte()
    val KEY_5 = 0x22.toByte()
    val KEY_6 = 0x23.toByte()
    val KEY_7 = 0x24.toByte()
    val KEY_8 = 0x25.toByte()
    val KEY_9 = 0x26.toByte()
    val KEY_0 = 0x27.toByte()

    val KEY_ENTER = 0x28.toByte()
    val KEY_ESCAPE = 0x29.toByte()
    val KEY_BACKSPACE = 0x2A.toByte()
    val KEY_TAB = 0x2B.toByte()
    val KEY_SPACE = 0x2C.toByte()
    val KEY_MINUS = 0x2D.toByte()
    val KEY_EQUAL = 0x2E.toByte()
    val KEY_LEFTBRACE = 0x2F.toByte()
    val KEY_RIGHTBRACE = 0x30.toByte()
    val KEY_BACKSLASH = 0x31.toByte()
    val KEY_HASHTILDE = 0x32.toByte()
    val KEY_SEMICOLON = 0x33.toByte()
    val KEY_APOSTROPHE = 0x34.toByte()
    val KEY_GRAVE = 0x35.toByte()
    val KEY_COMMA = 0x36.toByte()
    val KEY_DOT = 0x37.toByte()
    val KEY_SLASH = 0x38.toByte()
    val KEY_CAPSLOCK = 0x39.toByte()

    val KEY_F1 = 0x3A.toByte()
    val KEY_F2 = 0x3B.toByte()
    val KEY_F3 = 0x3C.toByte()
    val KEY_F4 = 0x3D.toByte()
    val KEY_F5 = 0x3E.toByte()
    val KEY_F6 = 0x3F.toByte()
    val KEY_F7 = 0x40.toByte()
    val KEY_F8 = 0x41.toByte()
    val KEY_F9 = 0x42.toByte()
    val KEY_F10 = 0x43.toByte()
    val KEY_F11 = 0x44.toByte()
    val KEY_F12 = 0x45.toByte()

    val KEY_PRINTSCREEN = 0x46.toByte()
    val KEY_SCROLLLOCK = 0x47.toByte()
    val KEY_PAUSE = 0x48.toByte()
    val KEY_INSERT = 0x49.toByte()
    val KEY_HOME = 0x4A.toByte()
    val KEY_PAGEUP = 0x4B.toByte()
    val KEY_DELETE = 0x4C.toByte()
    val KEY_END = 0x4D.toByte()
    val KEY_PAGEDOWN = 0x4E.toByte()
    val KEY_ARROW_RIGHT = 0x4F.toByte()
    val KEY_ARROW_LEFT = 0x50.toByte()
    val KEY_ARROW_DOWN = 0x51.toByte()
    val KEY_ARROW_UP = 0x52.toByte()

    val KEY_NUMLOCK = 0x53.toByte()
    val KEY_KPSLASH = 0x54.toByte()
    val KEY_KPASTERISK = 0x55.toByte()
    val KEY_KPMINUS = 0x56.toByte()
    val KEY_KPPLUS = 0x57.toByte()
    val KEY_KPENTER = 0x58.toByte()
    val KEY_KP1 = 0x59.toByte()
    val KEY_KP2 = 0x5A.toByte()
    val KEY_KP3 = 0x5B.toByte()
    val KEY_KP4 = 0x5C.toByte()
    val KEY_KP5 = 0x5D.toByte()
    val KEY_KP6 = 0x5E.toByte()
    val KEY_KP7 = 0x5F.toByte()
    val KEY_KP8 = 0x60.toByte()
    val KEY_KP9 = 0x61.toByte()
    val KEY_KP0 = 0x62.toByte()
    val KEY_KPDOT = 0x63.toByte()

    fun charToHid(char: Char): Pair<Byte, Byte> {
        return when (char) {
            in 'a'..'z' -> Pair(MOD_NONE, (char.code - 'a'.code + KEY_A).toByte())
            in 'A'..'Z' -> Pair(MOD_L_SHIFT, (char.code - 'A'.code + KEY_A).toByte())
            in '0'..'9' -> Pair(MOD_NONE, (char.code - '0'.code + KEY_1).toByte())
            '\n' -> Pair(MOD_NONE, KEY_ENTER)
            '\b' -> Pair(MOD_NONE, KEY_BACKSPACE)
            '\t' -> Pair(MOD_NONE, KEY_TAB)
            ' ' -> Pair(MOD_NONE, KEY_SPACE)

            '!' -> Pair(MOD_L_SHIFT, KEY_1)
            '@' -> Pair(MOD_L_SHIFT, KEY_2)
            '#' -> Pair(MOD_L_SHIFT, KEY_3)
            '$' -> Pair(MOD_L_SHIFT, KEY_4)
            '%' -> Pair(MOD_L_SHIFT, KEY_5)
            '^' -> Pair(MOD_L_SHIFT, KEY_6)
            '&' -> Pair(MOD_L_SHIFT, KEY_7)
            '*' -> Pair(MOD_L_SHIFT, KEY_8)
            '(' -> Pair(MOD_L_SHIFT, KEY_9)
            ')' -> Pair(MOD_L_SHIFT, KEY_0)

            '-' -> Pair(MOD_NONE, KEY_MINUS)
            '_' -> Pair(MOD_L_SHIFT, KEY_MINUS)
            '=' -> Pair(MOD_NONE, KEY_EQUAL)
            '+' -> Pair(MOD_L_SHIFT, KEY_EQUAL)
            '[' -> Pair(MOD_NONE, KEY_LEFTBRACE)
            '{' -> Pair(MOD_L_SHIFT, KEY_LEFTBRACE)
            ']' -> Pair(MOD_NONE, KEY_RIGHTBRACE)
            '}' -> Pair(MOD_L_SHIFT, KEY_RIGHTBRACE)
            '\\' -> Pair(MOD_NONE, KEY_BACKSLASH)
            '|' -> Pair(MOD_L_SHIFT, KEY_BACKSLASH)
            ';' -> Pair(MOD_NONE, KEY_SEMICOLON)
            ':' -> Pair(MOD_L_SHIFT, KEY_SEMICOLON)
            '\'' -> Pair(MOD_NONE, KEY_APOSTROPHE)
            '"' -> Pair(MOD_L_SHIFT, KEY_APOSTROPHE)
            '`' -> Pair(MOD_NONE, KEY_GRAVE)
            '~' -> Pair(MOD_L_SHIFT, KEY_GRAVE)
            ',' -> Pair(MOD_NONE, KEY_COMMA)
            '<' -> Pair(MOD_L_SHIFT, KEY_COMMA)
            '.' -> Pair(MOD_NONE, KEY_DOT)
            '>' -> Pair(MOD_L_SHIFT, KEY_DOT)
            '/' -> Pair(MOD_NONE, KEY_SLASH)
            '?' -> Pair(MOD_L_SHIFT, KEY_SLASH)

            else -> Pair(MOD_NONE, 0x00.toByte())
        }
    }
}
